CPX = "CPX"
CLUE = "CLUE"
PIXELS = "pixels"

CLUE_PIN = "D18"

CLUE = "CLUE"
BASE_64 = "display_base64"
IMG_DIR_NAME = "img"
SCREEN_HEIGHT_WIDTH = 240

BLINKA_BMP = "blinka.bmp"
CLUE_TERMINAL_LINE_HEIGHT = 16
CLUE_TERMINAL_LINE_NUM_MAX = 15
CLUE_TERMINAL_X_OFFSET = 15
CLUE_TERMINAL_Y_OFFSET = 5
CLUE_TERMINAL_LINE_BREAK_AMT = 37
