# This workflow will do a clean install of node dependencies, python dependencies, build the source code and run tests

name: CI

on:
  push:
    branches: [ dev, staging ]
  pull_request:
    branches: [ dev, staging ]

jobs:
  build:

    runs-on: [macos-latest, windows-latest, ubuntu-18.04]

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} and install npm dependencies
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.x
    - run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt
    - name: Run npm compile, format-check and test
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run compile
    - run: npm run check
    - run: npm test
